# Generated by Django 2.2.5 on 2022-04-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220415_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
