# Generated by Django 2.2.5 on 2022-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_board_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
