# Generated by Django 2.2.5 on 2022-04-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Board'),
        ),
    ]
