# Generated by Django 2.2.5 on 2022-04-15 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_reply_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='board_num',
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='board_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Board'),
        ),
    ]
