# Generated by Django 4.0.4 on 2022-04-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_board_user_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
